---
name: Color-Library
version: 0.02
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: An easy-to-use and comprehensive named-color library
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Module::Pluggable: 0
build_requires:
  Test::More: 0
provides:
  Color::Library:
    file: lib/Color/Library.pm
    version: 0.02
  Color::Library::Color:
    file: lib/Color/Library/Color.pm
  Color::Library::Dictionary:
    file: lib/Color/Library/Dictionary.pm
  Color::Library::Dictionary::HTML:
    file: lib/Color/Library/Dictionary/HTML.pm
  Color::Library::Dictionary::IE:
    file: lib/Color/Library/Dictionary/IE.pm
  Color::Library::Dictionary::Mozilla:
    file: lib/Color/Library/Dictionary/Mozilla.pm
  Color::Library::Dictionary::NBS_ISCC:
    file: lib/Color/Library/Dictionary/NBS_ISCC.pm
  Color::Library::Dictionary::NBS_ISCC::A:
    file: lib/Color/Library/Dictionary/NBS_ISCC/A.pm
  Color::Library::Dictionary::NBS_ISCC::B:
    file: lib/Color/Library/Dictionary/NBS_ISCC/B.pm
  Color::Library::Dictionary::NBS_ISCC::F:
    file: lib/Color/Library/Dictionary/NBS_ISCC/F.pm
  Color::Library::Dictionary::NBS_ISCC::H:
    file: lib/Color/Library/Dictionary/NBS_ISCC/H.pm
  Color::Library::Dictionary::NBS_ISCC::M:
    file: lib/Color/Library/Dictionary/NBS_ISCC/M.pm
  Color::Library::Dictionary::NBS_ISCC::P:
    file: lib/Color/Library/Dictionary/NBS_ISCC/P.pm
  Color::Library::Dictionary::NBS_ISCC::R:
    file: lib/Color/Library/Dictionary/NBS_ISCC/R.pm
  Color::Library::Dictionary::NBS_ISCC::RC:
    file: lib/Color/Library/Dictionary/NBS_ISCC/RC.pm
  Color::Library::Dictionary::NBS_ISCC::S:
    file: lib/Color/Library/Dictionary/NBS_ISCC/S.pm
  Color::Library::Dictionary::NBS_ISCC::SC:
    file: lib/Color/Library/Dictionary/NBS_ISCC/SC.pm
  Color::Library::Dictionary::NBS_ISCC::TC:
    file: lib/Color/Library/Dictionary/NBS_ISCC/TC.pm
  Color::Library::Dictionary::Netscape:
    file: lib/Color/Library/Dictionary/Netscape.pm
  Color::Library::Dictionary::SVG:
    file: lib/Color/Library/Dictionary/SVG.pm
  Color::Library::Dictionary::Tango:
    file: lib/Color/Library/Dictionary/Tango.pm
  Color::Library::Dictionary::VACCC:
    file: lib/Color/Library/Dictionary/VACCC.pm
  Color::Library::Dictionary::WWW:
    file: lib/Color/Library/Dictionary/WWW.pm
  Color::Library::Dictionary::Windows:
    file: lib/Color/Library/Dictionary/Windows.pm
  Color::Library::Dictionary::X11:
    file: lib/Color/Library/Dictionary/X11.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
